apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-deployment
  labels:
    app: go-deployment
spec:
  selector:
    matchLabels:
      app: go-pod
  replicas: 3
  template:
    metadata:
      labels:
        app: go-pod
    spec:
      containers:
        - name: go-container
          image: ACCOUNT_ID.dkr.ecr.REGION.amazonaws.com/REPOSITORY:TAG
          ports:
          - containerPort: 8080 
