apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: my-eks-cluster
  region: ap-northeast-1

availabilityZones: ["ap-northeast-1a", "ap-northeast-1c"]

nodeGroups:
  - name: my-node
    instanceType: t3.medium
    desiredCapacity: 2
    minSize: 2
    maxSize: 5
    iam: 
      withAddonPolicies:
        imageBuilder: true
        autoScaler: true
        albIngress: true
