name: AWS EKS Deploy
on:
  push:
    branches:
      - "main"
      - "develop"
env:
  ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  DEPLOYMENT_NAME: dev-go-deployment
  REGION: ap-northeast-1
  REPOSITORY: myapp-dev-go
  IMAGE: go-app

permissions:
  id-token: write
  contents: read
jobs:
  aws-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: $REGION
      
      # Builds and pushes an image up to Elastic Container Registry
      - name: Build and push image to ECR
        run: |-
          aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-northeast-1.amazonaws.com
          docker build --tag  $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$REPOSITORY:$GITHUB_SHA .
          docker push $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$REPOSITORY:$GITHUB_SHA
    
