name: AWS EKS Deploy
on:
  push:
    branches:
      - "main"
      - "develop"
env:
  ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  DEPLOYMENT_NAME: dev-go-deployment
  REGION: ap-northeast-1
  REPOSITORY: myapp-dev-go
  CLUSTER_NAME: my-eks-cluster
  EKS_KUSTOMIZE_PATH: kubernetes/aws/overlays/dev

permissions:
  id-token: write
  contents: read
jobs:
  aws-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ap-northeast-1

      # Builds and pushes an image up to Elastic Container Registry
      - name: Build and push image to ECR
        run: |-
          aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-northeast-1.amazonaws.com
          docker build --tag  $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$REPOSITORY:$GITHUB_SHA .
          docker push $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$REPOSITORY:$GITHUB_SHA
    
      # Update kubeconfig
      - name: Update kubeconfig
        run: |-
          aws --region $REGION eks update-kubeconfig --name $CLUSTER_NAME --kubeconfig ./kubeconfig
          cp kubeconfig ${{ env.EKS_KUSTOMIZE_PATH }}
      # Set up kustomize
      - name: Set up Kustomize
        run: |-
          cd ${{ env.EKS_KUSTOMIZE_PATH }}
          curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
          chmod u+x ./kustomize
      # Deploy the Docker image to the EKS cluster
      - name: Deploy
        run: |-
          # replacing the image name in the k8s template
          cd ${{ env.EKS_KUSTOMIZE_PATH }}
          ./kustomize edit set image ACCOUNT_ID.dkr.ecr.REGION.amazonaws.com/REPOSITORY:TAG=$ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$REPOSITORY:$GITHUB_SHA
          ./kustomize build . | kubectl --kubeconfig=./kubeconfig apply -f -
          kubectl --kubeconfig=./kubeconfig rollout status deployment/$DEPLOYMENT_NAME
          kubectl --kubeconfig=./kubeconfig get services -o wide
