name: CI

on:
  pull_request:
    branches:
      - main
      - develop

  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Hadolint
        uses: brpaz/hadolint-action@master
